baseURL: "http://localhost/blog"
languageCode: "en-gb"
title: "Matthew Warman"
theme: "tale"

permalinks:
  posts: /:year/:month/:title/

menu:
  main:
    - identifier: posts
      name: Posts
      url: /

markup:
  highlight:
    style: hrdark

params:
  css:
    - custom.css
