baseURL: "http://localhost/blog"
languageCode: "en-gb"
title: "Matthew Warman"
theme: "tale"

disableKinds:
  - section
  - taxonomy
  - term

permalinks:
  posts: /:year/:month/:title/

menu:
  main:
    - identifier: posts
      name: Posts
      url: /

markup:
  highlight:
    style: hrdark

params:
  css:
    - css/custom.css
    - css/mermaid.css
